server:
  port: 8763

spring:
  application:
    name: gr-conf-springboot-admin
  security:
    user:
      name: admin
      password: admin

  # java -jar fakesmtp-2.0.jar -p 2525
  # https://threadminions.wordpress.com/2019/06/25/alert-with-spring-boot-admin-server/
  #mail:
  #  host: localhost
  #  port: 2525
  #  protocol: smtp

# Spring Boot Admin Configuration
  boot:
    admin:
      discovery:
        ignored-services: gr-conf-springboot-admin
      server:
        # To enable or disable admin server
        enabled: true
      # To set title of admin server
      ui:
        title: Spring Boot Admin 
      monitor:
        # Time interval in ms to update the status of applications with 
        # expired status-informations.
        status-interval: 15000
        # To set lifetime of status. 
        # The status won't be updated as long the last status isn't expired.
        status-lifetime: 15000
        # Default number of retries for failed requests.
        # retry is available only for GET requests.
        default-retries: 2
      # To set context path of admin server
      context-path: /
      routes:
        endpoints: info
      #notify:
      #  mail:
      #    to: jihed@gmail.com, chaabane@gmail.com
      #    enabled: true

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


